import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from '@/lib/context/UserContext';
import { poppins } from '@/lib/font';
import { Toaster } from '@edge-ui/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <UserProvider>{children}</UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
